/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// export const projectId = "trbtloejeinczsabzivx"
// export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYnRsb2VqZWluY3pzYWJ6aXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5MTkxMjcsImV4cCI6MjA4MDQ5NTEyN30.l2owutqMClYEF96fuwCsiSaNgjnBLptZ3i0v9qALxCQ"

/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yuazbbilnbmfxffaedys"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YXpiYmlsbmJtZnhmZmFlZHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4NzUxODgsImV4cCI6MjEwNTQ1MTE4OH0.wVdyDoLkCc5Ta65ynWeRPTY9iBth_3ClXm-2qW7QGas"